# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_shaart.ui'
#
# Created: Tue Feb 25 13:55:22 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TheMainWindow(object):
    def setupUi(self, TheMainWindow):
        TheMainWindow.setObjectName(_fromUtf8("TheMainWindow"))
        TheMainWindow.resize(951, 590)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TheMainWindow.sizePolicy().hasHeightForWidth())
        TheMainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("shaart_logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TheMainWindow.setWindowIcon(icon)
        self.thecentralwidget = QtGui.QWidget(TheMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thecentralwidget.sizePolicy().hasHeightForWidth())
        self.thecentralwidget.setSizePolicy(sizePolicy)
        self.thecentralwidget.setObjectName(_fromUtf8("thecentralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.thecentralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.thecentralwidget)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabEquation = QtGui.QWidget()
        self.tabEquation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabEquation.setAutoFillBackground(False)
        self.tabEquation.setObjectName(_fromUtf8("tabEquation"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tabEquation)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_26 = QtGui.QLabel(self.tabEquation)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_28.addWidget(self.label_26)
        self.verticalLayout_14.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_27 = QtGui.QLabel(self.tabEquation)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_34.addWidget(self.label_27)
        self.eqnduration_lineEdit = QtGui.QLineEdit(self.tabEquation)
        self.eqnduration_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.eqnduration_lineEdit.setObjectName(_fromUtf8("eqnduration_lineEdit"))
        self.horizontalLayout_34.addWidget(self.eqnduration_lineEdit)
        self.label_28 = QtGui.QLabel(self.tabEquation)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_34.addWidget(self.label_28)
        self.eqnsr_lineEdit = QtGui.QLineEdit(self.tabEquation)
        self.eqnsr_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.eqnsr_lineEdit.setObjectName(_fromUtf8("eqnsr_lineEdit"))
        self.horizontalLayout_34.addWidget(self.eqnsr_lineEdit)
        self.verticalLayout_14.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.textBrowser = QtGui.QTextBrowser(self.tabEquation)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.horizontalLayout_30.addWidget(self.textBrowser)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_25 = QtGui.QLabel(self.tabEquation)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_31.addWidget(self.label_25)
        self.equation_lineEdit = QtGui.QLineEdit(self.tabEquation)
        self.equation_lineEdit.setObjectName(_fromUtf8("equation_lineEdit"))
        self.horizontalLayout_31.addWidget(self.equation_lineEdit)
        self.verticalLayout_14.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.eq_go_pushButton = QtGui.QPushButton(self.tabEquation)
        self.eq_go_pushButton.setObjectName(_fromUtf8("eq_go_pushButton"))
        self.horizontalLayout_32.addWidget(self.eq_go_pushButton)
        self.verticalLayout_14.addLayout(self.horizontalLayout_32)
        self.tabWidget.addTab(self.tabEquation, _fromUtf8(""))
        self.tabPlayRec = QtGui.QWidget()
        self.tabPlayRec.setObjectName(_fromUtf8("tabPlayRec"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tabPlayRec)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_30 = QtGui.QLabel(self.tabPlayRec)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_29.addWidget(self.label_30)
        self.verticalLayout_13.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabPlayRec)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 19, 861, 71))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_35.setMargin(0)
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.radioButton_3 = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.horizontalLayout_35.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.horizontalLayout_35.addWidget(self.radioButton_4)
        self.horizontalLayout_24.addWidget(self.groupBox_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.groupBox = QtGui.QGroupBox(self.tabPlayRec)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 861, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_33.setMargin(0)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_33.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_33.addWidget(self.radioButton_2)
        self.horizontalLayout_25.addWidget(self.groupBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_24 = QtGui.QLabel(self.tabPlayRec)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_27.addWidget(self.label_24)
        self.lineEdit_playrec_rate = QtGui.QLineEdit(self.tabPlayRec)
        self.lineEdit_playrec_rate.setObjectName(_fromUtf8("lineEdit_playrec_rate"))
        self.horizontalLayout_27.addWidget(self.lineEdit_playrec_rate)
        self.label_29 = QtGui.QLabel(self.tabPlayRec)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_27.addWidget(self.label_29)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.pushButton_playrec_go = QtGui.QPushButton(self.tabPlayRec)
        self.pushButton_playrec_go.setObjectName(_fromUtf8("pushButton_playrec_go"))
        self.horizontalLayout_26.addWidget(self.pushButton_playrec_go)
        self.pushButton_playrec_stop = QtGui.QPushButton(self.tabPlayRec)
        self.pushButton_playrec_stop.setObjectName(_fromUtf8("pushButton_playrec_stop"))
        self.horizontalLayout_26.addWidget(self.pushButton_playrec_stop)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.tabWidget.addTab(self.tabPlayRec, _fromUtf8(""))
        self.tabConvolve = QtGui.QWidget()
        self.tabConvolve.setEnabled(True)
        self.tabConvolve.setObjectName(_fromUtf8("tabConvolve"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tabConvolve)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tabConvolve)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.verticalLayout_12.addWidget(self.textBrowser_2)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.checkBox_autocorr = QtGui.QCheckBox(self.tabConvolve)
        self.checkBox_autocorr.setObjectName(_fromUtf8("checkBox_autocorr"))
        self.horizontalLayout_23.addWidget(self.checkBox_autocorr)
        self.checkBox_timerev = QtGui.QCheckBox(self.tabConvolve)
        self.checkBox_timerev.setObjectName(_fromUtf8("checkBox_timerev"))
        self.horizontalLayout_23.addWidget(self.checkBox_timerev)
        self.checkBox_removefirsthalf = QtGui.QCheckBox(self.tabConvolve)
        self.checkBox_removefirsthalf.setObjectName(_fromUtf8("checkBox_removefirsthalf"))
        self.horizontalLayout_23.addWidget(self.checkBox_removefirsthalf)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.convolve_go_pushButton = QtGui.QPushButton(self.tabConvolve)
        self.convolve_go_pushButton.setObjectName(_fromUtf8("convolve_go_pushButton"))
        self.horizontalLayout_22.addWidget(self.convolve_go_pushButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.tabWidget.addTab(self.tabConvolve, _fromUtf8(""))
        self.tabWaveform = QtGui.QWidget()
        self.tabWaveform.setObjectName(_fromUtf8("tabWaveform"))
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.tabWaveform)
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.horizontalLayout_83 = QtGui.QHBoxLayout()
        self.horizontalLayout_83.setObjectName(_fromUtf8("horizontalLayout_83"))
        self.waveform_abs_checkBox = QtGui.QCheckBox(self.tabWaveform)
        self.waveform_abs_checkBox.setObjectName(_fromUtf8("waveform_abs_checkBox"))
        self.horizontalLayout_83.addWidget(self.waveform_abs_checkBox)
        self.waveform_env_checkBox = QtGui.QCheckBox(self.tabWaveform)
        self.waveform_env_checkBox.setObjectName(_fromUtf8("waveform_env_checkBox"))
        self.horizontalLayout_83.addWidget(self.waveform_env_checkBox)
        self.verticalLayout_38.addLayout(self.horizontalLayout_83)
        self.waveform = WaveformWidget(self.tabWaveform)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveform.sizePolicy().hasHeightForWidth())
        self.waveform.setSizePolicy(sizePolicy)
        self.waveform.setObjectName(_fromUtf8("waveform"))
        self.verticalLayout_38.addWidget(self.waveform)
        self.tabWidget.addTab(self.tabWaveform, _fromUtf8(""))
        self.tabrt60 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabrt60.sizePolicy().hasHeightForWidth())
        self.tabrt60.setSizePolicy(sizePolicy)
        self.tabrt60.setObjectName(_fromUtf8("tabrt60"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabrt60)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.rt60horizontalLayout = QtGui.QHBoxLayout()
        self.rt60horizontalLayout.setObjectName(_fromUtf8("rt60horizontalLayout"))
        self.inwavfileselectButton = QtGui.QPushButton(self.tabrt60)
        self.inwavfileselectButton.setObjectName(_fromUtf8("inwavfileselectButton"))
        self.rt60horizontalLayout.addWidget(self.inwavfileselectButton)
        self.rt60lineEdit = QtGui.QLineEdit(self.tabrt60)
        self.rt60lineEdit.setObjectName(_fromUtf8("rt60lineEdit"))
        self.rt60lineEdit.setReadOnly(True)
        self.rt60horizontalLayout.addWidget(self.rt60lineEdit)
        self.inwavfileBselectButton = QtGui.QPushButton(self.tabrt60)
        self.inwavfileBselectButton.setObjectName(_fromUtf8("inwavfileBselectButton"))
        self.rt60horizontalLayout.addWidget(self.inwavfileBselectButton)
        self.fileBlineEdit = QtGui.QLineEdit(self.tabrt60)
        self.fileBlineEdit.setObjectName(_fromUtf8("fileBlineEdit"))
        self.fileBlineEdit.setReadOnly(True)
        self.rt60horizontalLayout.addWidget(self.fileBlineEdit)
        self.rt60octavelabel = QtGui.QLabel(self.tabrt60)
        self.rt60octavelabel.setObjectName(_fromUtf8("rt60octavelabel"))
        self.rt60horizontalLayout.addWidget(self.rt60octavelabel)
        self.rt60comboBox = QtGui.QComboBox(self.tabrt60)
        self.rt60comboBox.setObjectName(_fromUtf8("rt60comboBox"))
        self.rt60comboBox.addItem(_fromUtf8(""))
        self.rt60comboBox.addItem(_fromUtf8(""))
        self.rt60comboBox.addItem(_fromUtf8(""))
        self.rt60comboBox.addItem(_fromUtf8(""))
        self.rt60comboBox.addItem(_fromUtf8(""))
        self.rt60comboBox.addItem(_fromUtf8(""))
        self.rt60comboBox.addItem(_fromUtf8(""))
        self.rt60comboBox.addItem(_fromUtf8(""))
        self.rt60comboBox.addItem(_fromUtf8(""))
        self.rt60horizontalLayout.addWidget(self.rt60comboBox)
        self.verticalLayout_2.addLayout(self.rt60horizontalLayout)
        self.rt60 = Rt60Widget(self.tabrt60)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rt60.sizePolicy().hasHeightForWidth())
        self.rt60.setSizePolicy(sizePolicy)
        self.rt60.setObjectName(_fromUtf8("rt60"))
        self.verticalLayout_2.addWidget(self.rt60)
        self.tabWidget.addTab(self.tabrt60, _fromUtf8(""))
        self.tabpower = QtGui.QWidget()
        self.tabpower.setObjectName(_fromUtf8("tabpower"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabpower)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pwrspec = PwrSpecWidget(self.tabpower)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwrspec.sizePolicy().hasHeightForWidth())
        self.pwrspec.setSizePolicy(sizePolicy)
        self.pwrspec.setObjectName(_fromUtf8("pwrspec"))
        self.horizontalLayout_2.addWidget(self.pwrspec)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabpower, _fromUtf8(""))
        self.tabspectro = QtGui.QWidget()
        self.tabspectro.setObjectName(_fromUtf8("tabspectro"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabspectro)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_5 = QtGui.QLabel(self.tabspectro)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_21.addWidget(self.label_5)
        self.spectrocmcomboBox = QtGui.QComboBox(self.tabspectro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrocmcomboBox.sizePolicy().hasHeightForWidth())
        self.spectrocmcomboBox.setSizePolicy(sizePolicy)
        self.spectrocmcomboBox.setObjectName(_fromUtf8("spectrocmcomboBox"))
        self.spectrocmcomboBox.addItem(_fromUtf8(""))
        self.spectrocmcomboBox.addItem(_fromUtf8(""))
        self.spectrocmcomboBox.addItem(_fromUtf8(""))
        self.spectrocmcomboBox.addItem(_fromUtf8(""))
        self.spectrocmcomboBox.addItem(_fromUtf8(""))
        self.spectrocmcomboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_21.addWidget(self.spectrocmcomboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.spectro = SpectroWidget(self.tabspectro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectro.sizePolicy().hasHeightForWidth())
        self.spectro.setSizePolicy(sizePolicy)
        self.spectro.setObjectName(_fromUtf8("spectro"))
        self.horizontalLayout_3.addWidget(self.spectro)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tabspectro, _fromUtf8(""))
        self.tabwaterfall = QtGui.QWidget()
        self.tabwaterfall.setObjectName(_fromUtf8("tabwaterfall"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabwaterfall)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_4 = QtGui.QLabel(self.tabwaterfall)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_10.addWidget(self.label_4)
        self.water = WaterWidget(self.tabwaterfall)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.water.sizePolicy().hasHeightForWidth())
        self.water.setSizePolicy(sizePolicy)
        self.water.setObjectName(_fromUtf8("water"))
        self.verticalLayout_10.addWidget(self.water)
        self.verticalLayout_6.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tabwaterfall, _fromUtf8(""))
        self.tabmodecalc = QtGui.QWidget()
        self.tabmodecalc.setObjectName(_fromUtf8("tabmodecalc"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabmodecalc)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.tabmodecalc)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.speedlineEdit = QtGui.QLineEdit(self.tabmodecalc)
        self.speedlineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedlineEdit.setObjectName(_fromUtf8("speedlineEdit"))
        self.horizontalLayout_7.addWidget(self.speedlineEdit)
        self.label_2 = QtGui.QLabel(self.tabmodecalc)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.lengthlineEdit = QtGui.QLineEdit(self.tabmodecalc)
        self.lengthlineEdit.setText(_fromUtf8(""))
        self.lengthlineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lengthlineEdit.setObjectName(_fromUtf8("lengthlineEdit"))
        self.horizontalLayout_7.addWidget(self.lengthlineEdit)
        self.label_7 = QtGui.QLabel(self.tabmodecalc)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.widthlineEdit = QtGui.QLineEdit(self.tabmodecalc)
        self.widthlineEdit.setText(_fromUtf8(""))
        self.widthlineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widthlineEdit.setObjectName(_fromUtf8("widthlineEdit"))
        self.horizontalLayout_7.addWidget(self.widthlineEdit)
        self.label_8 = QtGui.QLabel(self.tabmodecalc)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.heightlineEdit = QtGui.QLineEdit(self.tabmodecalc)
        self.heightlineEdit.setText(_fromUtf8(""))
        self.heightlineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.heightlineEdit.setObjectName(_fromUtf8("heightlineEdit"))
        self.horizontalLayout_7.addWidget(self.heightlineEdit)
        self.label_6 = QtGui.QLabel(self.tabmodecalc)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.maxmodelineEdit = QtGui.QLineEdit(self.tabmodecalc)
        self.maxmodelineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxmodelineEdit.setObjectName(_fromUtf8("maxmodelineEdit"))
        self.horizontalLayout_7.addWidget(self.maxmodelineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.modesTextEdit = QtGui.QPlainTextEdit(self.tabmodecalc)
        self.modesTextEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modesTextEdit.sizePolicy().hasHeightForWidth())
        self.modesTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(16)
        font.setItalic(False)
        self.modesTextEdit.setFont(font)
        self.modesTextEdit.setUndoRedoEnabled(False)
        self.modesTextEdit.setReadOnly(True)
        self.modesTextEdit.setOverwriteMode(False)
        self.modesTextEdit.setObjectName(_fromUtf8("modesTextEdit"))
        self.horizontalLayout_5.addWidget(self.modesTextEdit)
        self.modegraph = ModeGraphWidget(self.tabmodecalc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modegraph.sizePolicy().hasHeightForWidth())
        self.modegraph.setSizePolicy(sizePolicy)
        self.modegraph.setObjectName(_fromUtf8("modegraph"))
        self.horizontalLayout_5.addWidget(self.modegraph)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tabmodecalc, _fromUtf8(""))
        self.tabsabine = QtGui.QWidget()
        self.tabsabine.setObjectName(_fromUtf8("tabsabine"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabsabine)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.tabsabine)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.sabinesslineEdit = QtGui.QLineEdit(self.tabsabine)
        self.sabinesslineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sabinesslineEdit.setObjectName(_fromUtf8("sabinesslineEdit"))
        self.horizontalLayout_4.addWidget(self.sabinesslineEdit)
        self.label_12 = QtGui.QLabel(self.tabsabine)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.sabinexlineEdit = QtGui.QLineEdit(self.tabsabine)
        self.sabinexlineEdit.setText(_fromUtf8(""))
        self.sabinexlineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sabinexlineEdit.setObjectName(_fromUtf8("sabinexlineEdit"))
        self.horizontalLayout_4.addWidget(self.sabinexlineEdit)
        self.label_13 = QtGui.QLabel(self.tabsabine)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_4.addWidget(self.label_13)
        self.sabineylineEdit = QtGui.QLineEdit(self.tabsabine)
        self.sabineylineEdit.setText(_fromUtf8(""))
        self.sabineylineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sabineylineEdit.setObjectName(_fromUtf8("sabineylineEdit"))
        self.horizontalLayout_4.addWidget(self.sabineylineEdit)
        self.label_14 = QtGui.QLabel(self.tabsabine)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_4.addWidget(self.label_14)
        self.sabinezlineEdit = QtGui.QLineEdit(self.tabsabine)
        self.sabinezlineEdit.setText(_fromUtf8(""))
        self.sabinezlineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sabinezlineEdit.setObjectName(_fromUtf8("sabinezlineEdit"))
        self.horizontalLayout_4.addWidget(self.sabinezlineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_15 = QtGui.QLabel(self.tabsabine)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_9.addWidget(self.label_15)
        self.floorcomboBox = QtGui.QComboBox(self.tabsabine)
        self.floorcomboBox.setObjectName(_fromUtf8("floorcomboBox"))
        self.floorcomboBox.addItem(_fromUtf8(""))
        self.floorcomboBox.addItem(_fromUtf8(""))
        self.floorcomboBox.addItem(_fromUtf8(""))
        self.floorcomboBox.addItem(_fromUtf8(""))
        self.floorcomboBox.addItem(_fromUtf8(""))
        self.floorcomboBox.addItem(_fromUtf8(""))
        self.floorcomboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.floorcomboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_17 = QtGui.QLabel(self.tabsabine)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_11.addWidget(self.label_17)
        self.ceilingcomboBox = QtGui.QComboBox(self.tabsabine)
        self.ceilingcomboBox.setObjectName(_fromUtf8("ceilingcomboBox"))
        self.ceilingcomboBox.addItem(_fromUtf8(""))
        self.ceilingcomboBox.addItem(_fromUtf8(""))
        self.ceilingcomboBox.addItem(_fromUtf8(""))
        self.ceilingcomboBox.addItem(_fromUtf8(""))
        self.ceilingcomboBox.addItem(_fromUtf8(""))
        self.ceilingcomboBox.addItem(_fromUtf8(""))
        self.ceilingcomboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.ceilingcomboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_18 = QtGui.QLabel(self.tabsabine)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.fwallcomboBox = QtGui.QComboBox(self.tabsabine)
        self.fwallcomboBox.setObjectName(_fromUtf8("fwallcomboBox"))
        self.fwallcomboBox.addItem(_fromUtf8(""))
        self.fwallcomboBox.addItem(_fromUtf8(""))
        self.fwallcomboBox.addItem(_fromUtf8(""))
        self.fwallcomboBox.addItem(_fromUtf8(""))
        self.fwallcomboBox.addItem(_fromUtf8(""))
        self.fwallcomboBox.addItem(_fromUtf8(""))
        self.fwallcomboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.fwallcomboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_19 = QtGui.QLabel(self.tabsabine)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_13.addWidget(self.label_19)
        self.bwallcomboBox = QtGui.QComboBox(self.tabsabine)
        self.bwallcomboBox.setObjectName(_fromUtf8("bwallcomboBox"))
        self.bwallcomboBox.addItem(_fromUtf8(""))
        self.bwallcomboBox.addItem(_fromUtf8(""))
        self.bwallcomboBox.addItem(_fromUtf8(""))
        self.bwallcomboBox.addItem(_fromUtf8(""))
        self.bwallcomboBox.addItem(_fromUtf8(""))
        self.bwallcomboBox.addItem(_fromUtf8(""))
        self.bwallcomboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.bwallcomboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_20 = QtGui.QLabel(self.tabsabine)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_14.addWidget(self.label_20)
        self.lwallcomboBox = QtGui.QComboBox(self.tabsabine)
        self.lwallcomboBox.setObjectName(_fromUtf8("lwallcomboBox"))
        self.lwallcomboBox.addItem(_fromUtf8(""))
        self.lwallcomboBox.addItem(_fromUtf8(""))
        self.lwallcomboBox.addItem(_fromUtf8(""))
        self.lwallcomboBox.addItem(_fromUtf8(""))
        self.lwallcomboBox.addItem(_fromUtf8(""))
        self.lwallcomboBox.addItem(_fromUtf8(""))
        self.lwallcomboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.lwallcomboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_16 = QtGui.QLabel(self.tabsabine)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        self.rwallcomboBox = QtGui.QComboBox(self.tabsabine)
        self.rwallcomboBox.setObjectName(_fromUtf8("rwallcomboBox"))
        self.rwallcomboBox.addItem(_fromUtf8(""))
        self.rwallcomboBox.addItem(_fromUtf8(""))
        self.rwallcomboBox.addItem(_fromUtf8(""))
        self.rwallcomboBox.addItem(_fromUtf8(""))
        self.rwallcomboBox.addItem(_fromUtf8(""))
        self.rwallcomboBox.addItem(_fromUtf8(""))
        self.rwallcomboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_15.addWidget(self.rwallcomboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_11 = QtGui.QLabel(self.tabsabine)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_16.addWidget(self.label_11)
        self.adultslineEdit = QtGui.QLineEdit(self.tabsabine)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adultslineEdit.sizePolicy().hasHeightForWidth())
        self.adultslineEdit.setSizePolicy(sizePolicy)
        self.adultslineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adultslineEdit.setObjectName(_fromUtf8("adultslineEdit"))
        self.horizontalLayout_16.addWidget(self.adultslineEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tabsabine)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.horizontalLayout_17.addWidget(self.plainTextEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.sabinercgraph = RcGraphWidget(self.tabsabine)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sabinercgraph.sizePolicy().hasHeightForWidth())
        self.sabinercgraph.setSizePolicy(sizePolicy)
        self.sabinercgraph.setObjectName(_fromUtf8("sabinercgraph"))
        self.verticalLayout_11.addWidget(self.sabinercgraph)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tabsabine, _fromUtf8(""))
        self.tabinvspectro = QtGui.QWidget()
        self.tabinvspectro.setObjectName(_fromUtf8("tabinvspectro"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabinvspectro)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_21 = QtGui.QLabel(self.tabinvspectro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_7.addWidget(self.label_21)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.is_img_pushButton = QtGui.QPushButton(self.tabinvspectro)
        self.is_img_pushButton.setObjectName(_fromUtf8("is_img_pushButton"))
        self.horizontalLayout_6.addWidget(self.is_img_pushButton)
        self.is_imname_lineEdit = QtGui.QLineEdit(self.tabinvspectro)
        self.is_imname_lineEdit.setObjectName(_fromUtf8("is_imname_lineEdit"))
        self.horizontalLayout_6.addWidget(self.is_imname_lineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_22 = QtGui.QLabel(self.tabinvspectro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_18.addWidget(self.label_22)
        self.is_duration_lineEdit = QtGui.QLineEdit(self.tabinvspectro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_duration_lineEdit.sizePolicy().hasHeightForWidth())
        self.is_duration_lineEdit.setSizePolicy(sizePolicy)
        self.is_duration_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.is_duration_lineEdit.setObjectName(_fromUtf8("is_duration_lineEdit"))
        self.horizontalLayout_18.addWidget(self.is_duration_lineEdit)
        self.label_23 = QtGui.QLabel(self.tabinvspectro)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_18.addWidget(self.label_23)
        self.is_rate_lineEdit = QtGui.QLineEdit(self.tabinvspectro)
        self.is_rate_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.is_rate_lineEdit.setObjectName(_fromUtf8("is_rate_lineEdit"))
        self.horizontalLayout_18.addWidget(self.is_rate_lineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.is_wav_pushButton = QtGui.QPushButton(self.tabinvspectro)
        self.is_wav_pushButton.setObjectName(_fromUtf8("is_wav_pushButton"))
        self.horizontalLayout_10.addWidget(self.is_wav_pushButton)
        self.is_wavname_lineEdit = QtGui.QLineEdit(self.tabinvspectro)
        self.is_wavname_lineEdit.setObjectName(_fromUtf8("is_wavname_lineEdit"))
        self.horizontalLayout_10.addWidget(self.is_wavname_lineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.is_go_pushButton = QtGui.QPushButton(self.tabinvspectro)
        self.is_go_pushButton.setObjectName(_fromUtf8("is_go_pushButton"))
        self.horizontalLayout_19.addWidget(self.is_go_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.is_status_label = QtGui.QLabel(self.tabinvspectro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_status_label.sizePolicy().hasHeightForWidth())
        self.is_status_label.setSizePolicy(sizePolicy)
        self.is_status_label.setText(_fromUtf8(""))
        self.is_status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.is_status_label.setObjectName(_fromUtf8("is_status_label"))
        self.horizontalLayout_20.addWidget(self.is_status_label)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.tabWidget.addTab(self.tabinvspectro, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        TheMainWindow.setCentralWidget(self.thecentralwidget)
        self.themenubar = QtGui.QMenuBar(TheMainWindow)
        self.themenubar.setGeometry(QtCore.QRect(0, 0, 951, 22))
        self.themenubar.setObjectName(_fromUtf8("themenubar"))
        self.menuFile = QtGui.QMenu(self.themenubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        TheMainWindow.setMenuBar(self.themenubar)
        self.theactionOpen = QtGui.QAction(TheMainWindow)
        self.theactionOpen.setObjectName(_fromUtf8("theactionOpen"))
        self.theactionQuit = QtGui.QAction(TheMainWindow)
        self.theactionQuit.setObjectName(_fromUtf8("theactionQuit"))
        self.theactionOpenB = QtGui.QAction(TheMainWindow)
        self.theactionOpenB.setObjectName(_fromUtf8("theactionOpenB"))
        self.theactionAbout = QtGui.QAction(TheMainWindow)
        self.theactionAbout.setObjectName(_fromUtf8("theactionAbout"))
        self.theactionSave = QtGui.QAction(TheMainWindow)
        self.theactionSave.setObjectName(_fromUtf8("theactionSave"))
        self.menuFile.addAction(self.theactionAbout)
        self.menuFile.addAction(self.theactionOpen)
        self.menuFile.addAction(self.theactionOpenB)
        self.menuFile.addAction(self.theactionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.theactionQuit)
        self.themenubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(TheMainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QObject.connect(self.sabinesslineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.sabinexlineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.sabineylineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.sabinezlineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.floorcomboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.ceilingcomboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.fwallcomboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.bwallcomboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.lwallcomboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.rwallcomboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.sabinercgraph.update)
        QtCore.QObject.connect(self.adultslineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.sabinercgraph.update)
        QtCore.QMetaObject.connectSlotsByName(TheMainWindow)

    def retranslateUi(self, TheMainWindow):
        TheMainWindow.setWindowTitle(_translate("TheMainWindow", "SHAART", None))
        self.label_26.setText(_translate("TheMainWindow", "Create/replace contents of File A based on an equation", None))
        self.label_27.setText(_translate("TheMainWindow", "Duration (s):", None))
        self.eqnduration_lineEdit.setText(_translate("TheMainWindow", "10", None))
        self.label_28.setText(_translate("TheMainWindow", "   Sample Rate (Hz):", None))
        self.eqnsr_lineEdit.setText(_translate("TheMainWindow", "44100", None))
        self.textBrowser.setHtml(_translate("TheMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">Predefined variables for use in equation:</span> </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">SR = sample rate </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NS = number of samples </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">t = time (in seconds)</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TMAX = Duration ( = NS/SR )</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">i = index (sample #, starting with 0) </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PI = 3.14159... </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ln() = Natural Log </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">log10() = log base ten </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Other standard math functions apply, e.g. exp() = e^()</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Also other Python functions (be careful here...)</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">Examples:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Exponential Sine Sweep between 20 Hz and 20,000 Hz, Amplitude 0.8 =  </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.8 * sin( 20 *2*PI*TMAX/ln(20000.0/20) * (exp(t/TMAX*ln(20000.0/20))-1) )</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">White Noise, Amplitude 0.5 =  0.5 * np.random.uniform(-1,1)</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">WARNING: This operation is slow.  You will likely see the \'spinning ball.\'  Be patient.</span></p></body></html>", None))
        self.label_25.setText(_translate("TheMainWindow", "EQUATION: Sound[i] =", None))
        self.equation_lineEdit.setText(_translate("TheMainWindow", "0.8 * sin( 20 *2*PI*TMAX/ln(20000.0/20) * (exp(t/TMAX*ln(20000.0/20))-1) )", None))
        self.eq_go_pushButton.setText(_translate("TheMainWindow", "GO!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEquation), _translate("TheMainWindow", "Equation", None))
        self.label_30.setText(_translate("TheMainWindow", "      NOTE: CURRENTLY THE PROGRAM ONLY \"PLAYS\" FILE A.  EVERYTHING ELSE IS JUST A PLACEHOLDER FOR FUTURE EXPANSION.", None))
        self.groupBox_2.setTitle(_translate("TheMainWindow", "FileA:", None))
        self.radioButton_3.setText(_translate("TheMainWindow", "Play", None))
        self.radioButton_4.setText(_translate("TheMainWindow", "Record", None))
        self.groupBox.setTitle(_translate("TheMainWindow", "FileB:", None))
        self.radioButton.setText(_translate("TheMainWindow", "Play", None))
        self.radioButton_2.setText(_translate("TheMainWindow", "Record", None))
        self.label_24.setText(_translate("TheMainWindow", "Sample Rate for Recording:", None))
        self.lineEdit_playrec_rate.setText(_translate("TheMainWindow", "44100", None))
        self.label_29.setText(_translate("TheMainWindow", "Hz", None))
        self.pushButton_playrec_go.setText(_translate("TheMainWindow", "GO", None))
        self.pushButton_playrec_stop.setText(_translate("TheMainWindow", "STOP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlayRec), _translate("TheMainWindow", "Play/Rec", None))
        self.textBrowser_2.setHtml(_translate("TheMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600;\">Convolves File A (e.g. music) with File B (e.g., impulse response)</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600;\">Places result in File A</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">To construct an impulse response from a sine sweep:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Let File A = original test signal,  File B = recorded room response,</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\"> and make sure &quot;Time Reverse File A&quot; is selected</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">&quot;Remove First Half of Result&quot; is typically used both for:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">- eliminating pre-ringing from constructed impulse responses</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">- eliminating redundant (t&lt;0) info from autocorrelation </span></p></body></html>", None))
        self.checkBox_autocorr.setText(_translate("TheMainWindow", "Autocorrelation (Convolve A with A)                            ", None))
        self.checkBox_timerev.setText(_translate("TheMainWindow", "Time-Reverse File A ", None))
        self.checkBox_removefirsthalf.setText(_translate("TheMainWindow", "Remove First Half of Result", None))
        self.convolve_go_pushButton.setText(_translate("TheMainWindow", "GO!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConvolve), _translate("TheMainWindow", "Convolve", None))
        self.waveform_abs_checkBox.setText(_translate("TheMainWindow", "Absolute Value", None))
        self.waveform_env_checkBox.setText(_translate("TheMainWindow", "Envelope Only", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWaveform), _translate("TheMainWindow", "Waveform", None))
        self.inwavfileselectButton.setText(_translate("TheMainWindow", "File A:", None))
        self.inwavfileBselectButton.setText(_translate("TheMainWindow", "File B:", None))
        self.rt60octavelabel.setText(_translate("TheMainWindow", "Octave:", None))
        self.rt60comboBox.setItemText(0, _translate("TheMainWindow", "All", None))
        self.rt60comboBox.setItemText(1, _translate("TheMainWindow", "125 Hz", None))
        self.rt60comboBox.setItemText(2, _translate("TheMainWindow", "250 Hz", None))
        self.rt60comboBox.setItemText(3, _translate("TheMainWindow", "500 Hz", None))
        self.rt60comboBox.setItemText(4, _translate("TheMainWindow", "1000 Hz", None))
        self.rt60comboBox.setItemText(5, _translate("TheMainWindow", "2000 Hz", None))
        self.rt60comboBox.setItemText(6, _translate("TheMainWindow", "4000 Hz", None))
        self.rt60comboBox.setItemText(7, _translate("TheMainWindow", "8000 Hz", None))
        self.rt60comboBox.setItemText(8, _translate("TheMainWindow", "16000 Hz", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabrt60), _translate("TheMainWindow", "RT60", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabpower), _translate("TheMainWindow", "Power", None))
        self.label_5.setText(_translate("TheMainWindow", "Color Map:", None))
        self.spectrocmcomboBox.setItemText(0, _translate("TheMainWindow", "Heat", None))
        self.spectrocmcomboBox.setItemText(1, _translate("TheMainWindow", "Rainbow", None))
        self.spectrocmcomboBox.setItemText(2, _translate("TheMainWindow", "Reverse Rainbow", None))
        self.spectrocmcomboBox.setItemText(3, _translate("TheMainWindow", "Grays", None))
        self.spectrocmcomboBox.setItemText(4, _translate("TheMainWindow", "Blues", None))
        self.spectrocmcomboBox.setItemText(5, _translate("TheMainWindow", "NCAR", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabspectro), _translate("TheMainWindow", "Spectrogram", None))
        self.label_4.setText(_translate("TheMainWindow", "Warning: This can be very slow for large data sets.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabwaterfall), _translate("TheMainWindow", "Waterfall", None))
        self.label.setText(_translate("TheMainWindow", "Sound Speed:", None))
        self.speedlineEdit.setText(_translate("TheMainWindow", "1140", None))
        self.label_2.setText(_translate("TheMainWindow", "Room Dimensions:  X:", None))
        self.label_7.setText(_translate("TheMainWindow", "Y:", None))
        self.label_8.setText(_translate("TheMainWindow", "Z:", None))
        self.label_6.setText(_translate("TheMainWindow", "Max Mode #:", None))
        self.maxmodelineEdit.setText(_translate("TheMainWindow", "10", None))
        self.modesTextEdit.setPlainText(_translate("TheMainWindow", "Freq (Hz)  Nx Ny Nz\n"
"---------  -- -- --\n"
"", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabmodecalc), _translate("TheMainWindow", "Mode Calc", None))
        self.label_3.setText(_translate("TheMainWindow", "Sound Speed (ft/s)", None))
        self.sabinesslineEdit.setText(_translate("TheMainWindow", "1140", None))
        self.label_12.setText(_translate("TheMainWindow", "Room Dimensions (ft):   X:", None))
        self.label_13.setText(_translate("TheMainWindow", "Y:", None))
        self.label_14.setText(_translate("TheMainWindow", "Z:", None))
        self.label_15.setText(_translate("TheMainWindow", "Floor (XY):", None))
        self.floorcomboBox.setItemText(0, _translate("TheMainWindow", "Concrete", None))
        self.floorcomboBox.setItemText(1, _translate("TheMainWindow", "Glass", None))
        self.floorcomboBox.setItemText(2, _translate("TheMainWindow", "Plasterboard", None))
        self.floorcomboBox.setItemText(3, _translate("TheMainWindow", "Plywood", None))
        self.floorcomboBox.setItemText(4, _translate("TheMainWindow", "Carpet", None))
        self.floorcomboBox.setItemText(5, _translate("TheMainWindow", "Curtains", None))
        self.floorcomboBox.setItemText(6, _translate("TheMainWindow", "Acoustical Board", None))
        self.label_17.setText(_translate("TheMainWindow", "Ceiling (XY):", None))
        self.ceilingcomboBox.setItemText(0, _translate("TheMainWindow", "Concrete", None))
        self.ceilingcomboBox.setItemText(1, _translate("TheMainWindow", "Glass", None))
        self.ceilingcomboBox.setItemText(2, _translate("TheMainWindow", "Plasterboard", None))
        self.ceilingcomboBox.setItemText(3, _translate("TheMainWindow", "Plywood", None))
        self.ceilingcomboBox.setItemText(4, _translate("TheMainWindow", "Carpet", None))
        self.ceilingcomboBox.setItemText(5, _translate("TheMainWindow", "Curtains", None))
        self.ceilingcomboBox.setItemText(6, _translate("TheMainWindow", "Acoustical Board", None))
        self.label_18.setText(_translate("TheMainWindow", "Front wall (XZ):", None))
        self.fwallcomboBox.setItemText(0, _translate("TheMainWindow", "Concrete", None))
        self.fwallcomboBox.setItemText(1, _translate("TheMainWindow", "Glass", None))
        self.fwallcomboBox.setItemText(2, _translate("TheMainWindow", "Plasterboard", None))
        self.fwallcomboBox.setItemText(3, _translate("TheMainWindow", "Plywood", None))
        self.fwallcomboBox.setItemText(4, _translate("TheMainWindow", "Carpet", None))
        self.fwallcomboBox.setItemText(5, _translate("TheMainWindow", "Curtains", None))
        self.fwallcomboBox.setItemText(6, _translate("TheMainWindow", "Acoustical Board", None))
        self.label_19.setText(_translate("TheMainWindow", "Back wall (XZ):", None))
        self.bwallcomboBox.setItemText(0, _translate("TheMainWindow", "Concrete", None))
        self.bwallcomboBox.setItemText(1, _translate("TheMainWindow", "Glass", None))
        self.bwallcomboBox.setItemText(2, _translate("TheMainWindow", "Plasterboard", None))
        self.bwallcomboBox.setItemText(3, _translate("TheMainWindow", "Plywood", None))
        self.bwallcomboBox.setItemText(4, _translate("TheMainWindow", "Carpet", None))
        self.bwallcomboBox.setItemText(5, _translate("TheMainWindow", "Curtains", None))
        self.bwallcomboBox.setItemText(6, _translate("TheMainWindow", "Acoustical Board", None))
        self.label_20.setText(_translate("TheMainWindow", "Left wall (YZ):", None))
        self.lwallcomboBox.setItemText(0, _translate("TheMainWindow", "Concrete", None))
        self.lwallcomboBox.setItemText(1, _translate("TheMainWindow", "Glass", None))
        self.lwallcomboBox.setItemText(2, _translate("TheMainWindow", "Plasterboard", None))
        self.lwallcomboBox.setItemText(3, _translate("TheMainWindow", "Plywood", None))
        self.lwallcomboBox.setItemText(4, _translate("TheMainWindow", "Carpet", None))
        self.lwallcomboBox.setItemText(5, _translate("TheMainWindow", "Curtains", None))
        self.lwallcomboBox.setItemText(6, _translate("TheMainWindow", "Acoustical Board", None))
        self.label_16.setText(_translate("TheMainWindow", "Right wall (YZ):", None))
        self.rwallcomboBox.setItemText(0, _translate("TheMainWindow", "Concrete", None))
        self.rwallcomboBox.setItemText(1, _translate("TheMainWindow", "Glass", None))
        self.rwallcomboBox.setItemText(2, _translate("TheMainWindow", "Plasterboard", None))
        self.rwallcomboBox.setItemText(3, _translate("TheMainWindow", "Plywood", None))
        self.rwallcomboBox.setItemText(4, _translate("TheMainWindow", "Carpet", None))
        self.rwallcomboBox.setItemText(5, _translate("TheMainWindow", "Curtains", None))
        self.rwallcomboBox.setItemText(6, _translate("TheMainWindow", "Acoustical Board", None))
        self.label_11.setText(_translate("TheMainWindow", "Adults in seats:", None))
        self.adultslineEdit.setText(_translate("TheMainWindow", "0", None))
        self.plainTextEdit.setPlainText(_translate("TheMainWindow", "Absorption Coefficients (Sab/ft^2)\n"
"-----------------------------------\n"
"Freq (Hz):    125   500  1000  2000 \n"
"-----------------------------------\n"
"Concrete     0.01  0.02  0.02  0.02 \n"
"Glass        0.19  0.06  0.04  0.03 \n"
"Plasterboard 0.20  0.10  0.08  0.04  \n"
"Plywood      0.45  0.13  0.11  0.10  \n"
"Carpet       0.10  0.30  0.35  0.50 \n"
"Curtains     0.05  0.25  0.35  0.40 \n"
"Acous Board  0.25  0.80  0.90  0.90 \n"
"\n"
"Adult (Sab):  3.0   4.5   5.0   5.2\n"
"", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabsabine), _translate("TheMainWindow", "Sabine Calc", None))
        self.label_21.setText(_translate("TheMainWindow", "Encode an image as a WAV file", None))
        self.is_img_pushButton.setText(_translate("TheMainWindow", "Input Image File:", None))
        self.label_22.setText(_translate("TheMainWindow", "Image Duration (s):        ", None))
        self.is_duration_lineEdit.setText(_translate("TheMainWindow", "8", None))
        self.label_23.setText(_translate("TheMainWindow", "Sample Rate (Hz):", None))
        self.is_rate_lineEdit.setText(_translate("TheMainWindow", "48000", None))
        self.is_wav_pushButton.setText(_translate("TheMainWindow", "Output WAV File:", None))
        self.is_go_pushButton.setText(_translate("TheMainWindow", "GO!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabinvspectro), _translate("TheMainWindow", "invSpectro", None))
        self.menuFile.setTitle(_translate("TheMainWindow", "File", None))
        self.theactionOpen.setText(_translate("TheMainWindow", "Open File A", None))
        self.theactionOpen.setToolTip(_translate("TheMainWindow", "Open File A", None))
        self.theactionOpen.setShortcut(_translate("TheMainWindow", "Ctrl+O", None))
        self.theactionQuit.setText(_translate("TheMainWindow", "Quit", None))
        self.theactionOpenB.setText(_translate("TheMainWindow", "Open File B", None))
        self.theactionOpenB.setToolTip(_translate("TheMainWindow", "Open File B", None))
        self.theactionOpenB.setShortcut(_translate("TheMainWindow", "Ctrl+B", None))
        self.theactionAbout.setText(_translate("TheMainWindow", "About", None))
        self.theactionSave.setText(_translate("TheMainWindow", "Save File A", None))
        self.theactionSave.setShortcut(_translate("TheMainWindow", "Ctrl+S", None))

from rcgraphwidget import RcGraphWidget
from waveformwidget import WaveformWidget
from rt60widget import Rt60Widget
from spectrowidget import SpectroWidget
from waterwidget import WaterWidget
from pwrspecwidget import PwrSpecWidget
from modegraphwidget import ModeGraphWidget
